#lang info
(define deps '("base"))

(define base00 #(31 36 48))
(define base03 #(92 103 115))
(define base04 #(242 158 116))
(define base05 #(203 204 198))
(define base07 #(247 247 247))
(define base08 #(255 51 51))
(define base09 #(212 191 255))
(define base0A #(253 237 2))
(define base0B #(186 230 126))
(define base0C #(97 207 230))
(define base0D #(255 213 128))
(define base0E #(255 167 89))
(define base0F #(205 171 83))

(define framework:color-schemes
    `(#hash((name . "ayu mirage")
            (white-on-black-base? . #f)
            (colors
             .
             ((framework:basic-canvas-background ,base00)
              (framework:default-text-color ,base05)
              (framework:misspelled-text-color ,base08)
              (framework:paren-match-color ,base03)
              (drracket:check-syntax:free-variable ,base0E)
              (drracket:check-syntax:imported ,base0D)
              (drracket:check-syntax:lexically-bound ,base0C)
              (drracket:check-syntax:my-obligation-style-pref ,base09)
              (drracket:check-syntax:set!d ,base0B)
              (drracket:check-syntax:unk-obligation-style-pref ,base08)
              (drracket:check-syntax:unused-require ,base08)
              (drracket:read-eval-print-loop:error-color ,base08)
              (drracket:read-eval-print-loop:out-color ,base09)
              (drracket:read-eval-print-loop:value-color ,base0D)
              (framework:syntax-color:scheme:comment ,base03)
              (framework:syntax-color:scheme:constant ,base09)
              (framework:syntax-color:scheme:error ,base08)
              (framework:syntax-color:scheme:hash-colon-keyword ,base0C)
              (framework:syntax-color:scheme:keyword ,base0E)
              (framework:syntax-color:scheme:other ,base05)
              (framework:syntax-color:scheme:parenthesis ,base04)
              (framework:syntax-color:scheme:string ,base0B)
              (framework:syntax-color:scheme:symbol ,base0D)
              (framework:syntax-color:scheme:text ,base05)
              (plt:htdp:test-coverage-off ,base08)
              (plt:htdp:test-coverage-on ,base0B)
              (plt:module-language:test-coverage-off ,base08)
              (plt:module-language:test-coverage-on ,base0B))))))
  